language: go
sudo: false
before_install:
        - .travis/gofmt.sh
        - go get -u github.com/golang/lint/golint
        - .travis/golint.sh
        - go get github.com/mattn/goveralls
script:
        - $HOME/gopath/bin/goveralls -service=travis-ci

