language: go
sudo: false
before_install:
        - .travis/longlines.sh
        - .travis/golangci-lint.sh
        - go get github.com/mattn/goveralls
script:
        - $HOME/gopath/bin/goveralls -service=travis-ci

